# GoReleaser configuration

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: "{{ .ProjectName }}"
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

# Use simpler snapshot naming to ensure compatibility
snapshot:
  name_template: "next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Explicitly configure GitHub Releases
release:
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
